# Generated by Django 4.1 on 2023-03-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="follower",
            name="user_twitter_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="following",
            name="user_twitter_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mutualfollower",
            name="user_twitter_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notfollowingback",
            name="user_twitter_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
