# Generated by Django 4.1 on 2023-03-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_follower_user_twitter_id_following_user_twitter_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="lang",
            field=models.CharField(blank=True, default=0, max_length=2),
            preserve_default=False,
        ),
    ]
