# Generated by Django 4.1 on 2023-03-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="lang",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
