# Generated by Django 4.1 on 2023-04-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_usertimeline_in_reply_to_screen_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertimeline",
            old_name="text",
            new_name="tweet",
        ),
        migrations.AddField(
            model_name="usertimeline",
            name="sentiment",
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="usertimeline",
            name="subjectivity",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
