# Generated by Django 4.1 on 2023-04-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_text_usertimeline_tweet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertimeline",
            name="subjectivity",
        ),
        migrations.AddField(
            model_name="usertimeline",
            name="polarity",
            field=models.FloatField(null=True),
        ),
    ]
