# Generated by Django 4.1 on 2023-04-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_usertimeline_subjectivity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertimeline",
            name="tweet_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
