# Generated by Django 4.1 on 2023-04-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_usertimeline_tweet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertimeline",
            name="quoted_status",
            field=models.TextField(blank=True, max_length=280),
        ),
    ]
