# Generated by Django 4.1 on 2023-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_follower_location_following_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_twitter_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
