# Generated by Django 4.1 on 2023-04-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_userprofile_user_twitter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutualfollower",
            name="profile_image_url",
            field=models.URLField(blank=True),
        ),
    ]
