# Generated by Django 4.1 on 2023-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_mutualfollower_profile_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=25)),
                ("prenom", models.CharField(max_length=25)),
            ],
        ),
    ]
