# Generated by Django 4.1 on 2023-04-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
